services:
  consul:
    image: consul:1.15
    container_name: consul-server
    ports:
      - "8500:8500" 
    command: agent -dev -client=0.0.0.0
    restart: unless-stopped
    networks:
      - traefik

  traefik:
    image: traefik:v3.1
    container_name: traefik  
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
    restart: unless-stopped
    networks:
      - traefik

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: MetaGrid
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - traefik


networks:
  traefik:
    external: true

volumes:
  postgres_data:
